### ISSUE TITLE
✔[TODO] 캐릭터 움직임 디벨롭 및 애니메이션 적용

### ISSUE THREAD

**Issue by SYEON10** [E-CyberGame/client#10]
## Due date (expected)

중간발표인 5월 24일을 목표로 함.

## ToDo

- [x] 캐릭터 움직임 디벨롭(가속, 감속, 점프 시 이동 추락)
- [x] 캐릭터 움직임에 따른 애니메이션 적용
- [x] 캐릭터 기본공격 움직임 구현(타격/피격 X)

**Comment by SYEON10** [comment]
대시, 감속/가속 점프 시 추락 등 움직임 미세 조정
