### ISSUE TITLE
✔[TODO]

### ISSUE THREAD

**Issue by SYEON10** [E-CyberGame/client#48]
## Due date (expected)

7주차 금요일

## ToDo(기능 리스트)

- [ ] B형 버프 - 기절(n초 동안 움직이지 못함)
- [ ] B형 버프 - 무적(n초 동안 타격을 받지 않음)
- [ ] 기물 내 있음을 감지(+기물 내 있을 때 B형 버프 적용)
- [ ] 위에서 구현한 기능을 바탕 실제 스킬 구현
- [ ] Photo Shot
- [ ] Challenge!
- [ ] 에너지 드링크
- [ ] 가호
- [ ] 에너지 폭발
- [ ] 크로스 어택
