### ISSUE TITLE
✔[TODO] 캐릭터 전반 인터페이스(설계) 개괄

### ISSUE THREAD

**Issue by SYEON10** [E-CyberGame/client#6]
## Due date (expected)

05-18 예정.

## ToDo

- [x] 캐릭터 움직임(상태) 인터페이스
- [x] 캐릭터 인풋 인터페이스
- [x] 캐릭터 타격 피격 인터페이스
- [x] 캐릭터 스킬 인터페이스
- [x] 캐릭터 버프/디버프 인터페이스(50%)

## Ect

캐릭터 상태패턴 적용 완료.
실제로 동작하는 것 확인(상하좌우)
스킬 개괄적인 구조 작성. 테스트 완료. (Debug.Log)
